openmrs/openmrs-contrib-qaframework

.gitignore
cypress.json
cypress/integration/cucumber/step_definitions/login.js
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
cypress/support/qa.js
cypress/tsconfig.json
package.json
pom.xml
src/test/java/org/openmrs/contrib/qaframework/RunTest.java
src/test/java/org/openmrs/contrib/qaframework/automation/AllergiesSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/ConditionsSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/FindPatientSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/LoginSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/RegistrationSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/Steps.java
src/test/java/org/openmrs/contrib/qaframework/automation/StylesGuideSteps.java
src/test/resources/cucumber.properties
src/test/resources/features/03-login/login.feature
src/test/resources/features/07-patient/findPatient.feature
src/test/resources/features/07-patient/patientRegistration.feature
src/test/resources/features/11-allergy/allergies.feature
src/test/resources/features/13-condition/conditions.feature
src/test/resources/features/stylesGuide.feature
tsconfig.json

tag a scenario @selenium to run with selenium and @cypress with run with cypress.
The 2 automation frameworks are running by default when compiling (mvn clean install) or testing (mvn clean test). Therefore avoid writing the same functionality in both frameworks to increase coverage. This has been written just for comparison

Supporting cypress and Selenium at the same time

---

.gitignore

Ticket ID: https://issues.openmrs.org/browse/RATEST-101
Description:
Disabled committing RunTest.java and test.properties in order to allow easy local testing

Temporarily ignore committing RunTest.java & test.properties

---

.gitignore

Reverts openmrs/openmrs-contrib-qaframework#17

Revert "RATEST-101: Temporarily ignore committing RunTest.java & test.properties"

---

.github/workflows/vitals-and-triaging.yml
README.md
package.json
src/test/java/org/openmrs/contrib/qaframework/RunTest.java
src/test/java/org/openmrs/contrib/qaframework/automation/VitalsAndTriagingSteps.java
src/test/resources/features/refapp-2.x/03-trackPatient/vitals.feature
src/test/resources/features/refapp-2.x/03-trackPatient/vitalsAndTriaging.feature

Ticket [ID](https://issues.openmrs.org/browse/RATEST-151)
Description -> E2E Vitals and triaging test workflow

RATEST-151: E2E Vitals and triaging test workflow

---

.github/workflows/clinical-visit.yml
README.md
package.json
src/test/java/org/openmrs/contrib/qaframework/RunTest.java
src/test/java/org/openmrs/contrib/qaframework/automation/ClinicalVisitSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/Steps.java
src/test/java/org/openmrs/contrib/qaframework/automation/VitalsAndTriagingSteps.java
src/test/resources/features/refapp-2.x/14-clinicalVisit/clinicalVisit.feature

Ticket I[D](https://issues.openmrs.org/browse/RATEST-154)
Description -> E2E Clinical visit test workflow

RATEST-154: E2E Clinical visit test workflow

---

README.md

[OCLOMRS-1017](https://issues.openmrs.org/browse/OCLOMRS-1017)
- Added a new personalized workflow for the dictionary manager and added its badge to the QA dashboard.

OCLOMRS-1017: Add a workflow badge for the dictionary manager tests

---

pom.xml

Ticket [ID](https://issues.openmrs.org/browse/RATEST-177)
Description -> Upgrade frontend maven plugin to 1.11.3

RATEST-177: Upgrade frontend maven plugin to 1.11.3

---

.github/workflows/clinical-visit.yml
.github/workflows/vitals-and-triaging.yml
README.md

Ticket [ID](https://issues.openmrs.org/browse/RATEST-176)
Description -> Refactor the ReadMe file for better QA Dashboard 2.x RefApp test display

RATEST-176: Updating README.md file

---

README.md

Proposed update to QA Dashboard

---

.github/workflows/refapp-2x-clinical-visit.yml
.github/workflows/refapp-2x-vitals-and-triaging.yml
package.json
src/test/java/org/openmrs/contrib/qaframework/automation/Steps.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-187)
Description -> Refactor refapp-2x test workflows configurations to a more clear names

RATEST-187: Refactor refapp-2x test workflows configurations to a more clear names

---

README.md

Ticket [ID](https://issues.openmrs.org/browse/RATEST-190)
Description -> Activate clinical visit test and vitals& triaging test status badge

RATEST-190: Refactoring clinical visit test and vitals& triaging test configurations to activate their status badges

---

README.md

The purpose of this PR is to fix https://issues.openmrs.org/browse/RATEST-195
https://github.com/jayasanka-sack/openmrs-contrib-qaframework/blob/RATEST-195/README.md
Update the readme with the following sections
- Setting up the project
- Running tests
- File structure
- Writing a new test
- Creating a GitHub workflow
- Environment variables

RATEST-195: Add 3.x documentation to the readme file

---

.github/workflows/refapp-2x-clinical-visit.yml
.github/workflows/refapp-2x-vitals-and-triaging.yml
package.json

Ticket [ID](https://issues.openmrs.org/browse/RATEST-202)
Description -> Refactor refapp 2.x clinical visit and vitals-and triaging workflow tests

RATEST-202: Rename refapp 2.x clinical visit and vitals-and-triaging workflow tests

---

src/test/resources/features/refapp-3.x/04-clinical-visit/clinical-visit.feature

The purpose of this PR is to fix [RATEST-215](https://issues.openmrs.org/browse/RATEST-215).
Fix the failing scenario (Conditions page) by clicking on the correct menu item.
(Previously it clicked on the allergies menu now it clicks on the Conditions menu)

RATEST-215: Fix 3.x clinical visit workflow

---

.github/workflows/refapp-2x-registration.yml
README.md
package.json
src/test/java/org/openmrs/contrib/qaframework/RunTest.java
src/test/java/org/openmrs/contrib/qaframework/automation/FindPatientSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/RegistrationSteps.java
src/test/resources/features/refapp-2.x/03-createPatient/patientRegistration.feature
src/test/resources/org/openmrs/uitestframework/test.properties

https://issues.openmrs.org/browse/RATEST-214

RATEST-150R:New E2E Test For Registration Workflow

---

.github/workflows/refapp-2x-user-account.yml
README.md
package.json
src/test/java/org/openmrs/contrib/qaframework/RunTest.java
src/test/java/org/openmrs/contrib/qaframework/automation/UserAccountSteps.java
src/test/resources/features/refapp-2.x/06-user/users.feature

Ticket [ID](https://issues.openmrs.org/browse/RATEST-157)
Description -> E2E User account workflow test

RATEST-157: E2E User account workflow test

---

.github/workflows/refapp-2x-findPatient.yml
README.md
package.json
src/test/java/org/openmrs/contrib/qaframework/RunTest.java
src/test/java/org/openmrs/contrib/qaframework/automation/FindPatientSteps.java
src/test/resources/features/refapp-2.x/03-trackPatient/findPatient.feature

https://issues.openmrs.org/browse/RATEST-221

RATEST-150S:New E2E Test For FindPatient Workflow

---

src/test/java/org/openmrs/contrib/qaframework/automation/FindPatientSteps.java
src/test/resources/features/refapp-2.x/03-trackPatient/findPatient.feature

https://issues.openmrs.org/browse/RATEST-230

RATEST-230:Use cucumber Examples Table to fetch  Patient name in findPatientSteps

---

src/test/java/org/openmrs/contrib/qaframework/automation/FindPatientSteps.java
src/test/resources/features/refapp-2.x/03-trackPatient/findPatient.feature

Reverts openmrs/openmrs-contrib-qaframework#115

Revert "RATEST-230:Use cucumber Examples Table to fetch  Patient name in findPatientSteps"

---

README.md

Table-view for QA Dashboard

---

cypress/integration/cucumber/step_definitions/refapp-3.x/01-login/login.js
cypress/integration/cucumber/step_definitions/refapp-3.x/02-search-and-registration/search-and-registration.js
cypress/integration/cucumber/step_definitions/refapp-3.x/03-settings/settings.js
cypress/integration/cucumber/step_definitions/refapp-3.x/04-clinical-visit/clinical-visit.js

Ticket [ID](https://issues.openmrs.org/browse/RATEST-227)
Description -> 3.x RefApp workflow tests are failing due to an error, unhandled promise rejection

RATEST-227: Adding event handler for the 3.x refapp workflow tests

---

README.md

Summary:
- Update the read me file

README: Get rid of tracking already developed workflow tests as under development, and Add a text 'Workflow Tests' on 3.x RefApp

---

pom.xml

Reverts openmrs/openmrs-contrib-qaframework#134

Revert "RATEST-238: Update refappuitests version to 2.13.0-SNAPSHOT"

---

cypress/integration/cucumber/step_definitions/refapp-3.x/04-clinical-visit/clinical-visit.js
src/test/resources/features/refapp-3.x/04-clinical-visit/clinical-visit.feature

The purpose of this PR is to fix [RATEST-247](https://issues.openmrs.org/browse/RATEST-247)
To give users confidence that the Form Entry Feature in the client visit workflow of the RefApp 3.x is working as expected.
Update the clinical-visit.feature with the Form entry feature
Write the E2E for Checking the form entry feature

RATEST-247: E2E: 3.x: Clinical visit: Form Entry

---

cypress/integration/cucumber/step_definitions/refapp-3.x/04-clinical-visit/clinical-visit.js

Purpose
The purpose of this PR is to fix [RATEST-252](https://issues.openmrs.org/browse/RATEST-252).
Approach
Update the 3.x clinical visit workflow to fix with the new user interface.
(There were some text changes with the new UI. By this pull request the 3.x clinical visit workflow has been updated to fit with the new user interface.)

RATEST-245: Update the 3.x clinical visit workflow E2E test to fit with new UI.

---

.github/workflows/refapp-2x-user-account.yml
package.json
src/test/resources/features/refapp-2.x/06-user/users.feature

Ticket [ID](https://issues.openmrs.org/browse/RATEST-253)
Description -> User account workflow test is currently breaking with Bambo though passing with GitHub Actions. See the full build log at https://ci.openmrs.org/browse/CONTRIB-QA-FRAMEWORK-938/log

RATEST-253: Temporarily ignore UserAccount workflow test not to run with ci

---

.github/workflows/refapp-3x-vitals-and-triage.yml
README.md
cypress/integration/cucumber/step_definitions/refapp-3.x/05-vitals-and-triage/vitals-and-triage.js
package.json
src/test/resources/features/refapp-3.x/04-clinical-visit/clinical-visit.feature
src/test/resources/features/refapp-3.x/05-vitals-and-triage/vitals-and-triage.feature

The purpose of this PR is to fix [MF-871](https://issues.openmrs.org/browse/MF-871)
To give users confidence that the vitals and triage workflow of the RefApp 3.x is working as expected.
Created the  `vitals-and-triage.feature` and the `vitals-and-triage.js`   
Write the E2E for Checking the test results
Update the `package.json` file
Create the  `vitals-and-triage.yml` workflow file
https://user-images.githubusercontent.com/43912578/137320277-e633c69f-6623-49df-8be8-cd2e5edb20e3.mp4

MF-871: 3.x: Implement Vitals and Triage workflow

---

.github/workflows/refapp-2x-user-account.yml
README.md
package.json
src/test/java/org/openmrs/contrib/qaframework/RunTest.java
src/test/java/org/openmrs/contrib/qaframework/automation/UserAccountSteps.java
src/test/resources/features/refapp-2.x/06-user/users.feature

Ticket [ID](https://issues.openmrs.org/browse/RATEST-250)
Description -> Restoring user account test into master after fixing ci build plan.

RATEST-250: Restore User account workflow test

---

src/test/java/org/openmrs/contrib/qaframework/automation/ClinicalVisitSteps.java
src/test/resources/features/refapp-2.x/14-clinicalVisit/clinicalVisit.feature

Ticket [ID](https://issues.openmrs.org/browse/RATEST-264)
Description -> Fix the clinical visit logic flow in 2.x RefApp test

RATEST-264: Fix the clinical visit logic flow in 2.x RefApp test

---

README.md

It wasn't clear what "Basic Dictionary Manager" meant, so added some text to clarify.

Add detail to "Basic Dictionary Manager" test suite

---

README.md
app.json
static.json

Ticket [ID](https://issues.openmrs.org/browse/RATEST-260)
Description-> Set up Heroku pipeline for deploying PRs' changes before merge action

RATEST-260: Set up Heroku pipeline for deploying PRs' changes before merge action

---

src/test/java/org/openmrs/contrib/qaframework/automation/VitalsAndTriagingSteps.java
src/test/java/org/openmrs/contrib/qaframework/page/EditVitalsPage.java
src/test/java/org/openmrs/contrib/qaframework/page/PatientVisitsDashboardPage.java
src/test/resources/features/refapp-2.x/03-trackPatient/vitalsAndTriaging.feature

Ticket -->[ RATEST-204](https://issues.openmrs.org/browse/RATEST-204)
Fixed ->-> Add extension for vitals and triaging workflow test and edit vitals page for this test

RATEST-204: Add extension for vitals and triaging workflow test

---

src/test/java/org/openmrs/contrib/qaframework/automation/ClinicalVisitSteps.java
src/test/resources/features/refapp-2.x/14-clinicalVisit/clinicalVisit.feature

Ticket url
https://issues.openmrs.org/browse/RATEST-225
Patient Dashboard adding/deleting Allergies and conditions

RATEST-225: E2E Clinical Visit Test: Patient Dashboard adding/deleting Allergies and conditions

---

.github/workflows/refapp-2x-edit-patient-demograpics.yml
.github/workflows/refapp-2x-patient-demograpics.yml
README.md
package.json
src/test/java/org/openmrs/contrib/qaframework/RunTest.java
src/test/java/org/openmrs/contrib/qaframework/automation/EditDemographicsAndContactInfoSteps.java
src/test/java/org/openmrs/contrib/qaframework/page/RegistrationEditSectionPage.java
src/test/java/org/openmrs/contrib/qaframework/page/RegistrationSummaryPage.java
src/test/resources/features/refapp-2.x/03-trackPatient/editDemographicsAndContactInfo.feature

Ticket [RATEST-226](https://issues.openmrs.org/browse/RATEST-226)
Fixed > > Patient Dashboard Editing Patient Demographics and Contact information.

RATEST-226: Editing Patient Demographics and Contact information

---

README.md

This was requested by christine to have sona dashboard to be part of the the dashboards for easy track.
cc @kdaud

adding sonaqube dashboard and sonaqube core into our dashboards

---

README.md

Reverts openmrs/openmrs-contrib-qaframework#232

Revert "adding sonaqube dashboard and sonaqube core into our dashboard"

---

README.md

cc @kdaud  because it was merged perhaps without reviews feel free to add more comments in this  new pr  thanks.

adding sonaqube dashboard  into our qa dashboard 

---

src/test/java/org/openmrs/contrib/qaframework/automation/AllergiesSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/ConditionsSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/FindPatientSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/InpatientSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/PageRejectedException.java
src/test/java/org/openmrs/contrib/qaframework/automation/UserAccountSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/VitalsAndTriagingSteps.java
src/test/java/org/openmrs/contrib/qaframework/page/AllergyPage.java
src/test/resources/features/refapp-2.x/06-user/users.feature

Ticket [ID](https://issues.openmrs.org/browse/RATEST-277)
Description -> Replace assertText() with assertPage() to improve the test run.

RATEST-277: Replace assertText() with assertPage() to improve the tests run

---

src/test/java/org/openmrs/contrib/qaframework/automation/AdvancedInstallSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/AllergiesSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/ClinicalVisitSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/ConditionsSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/FindPatientSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/InpatientSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/LoginSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/PostgresInstallSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/RegistrationSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/ReportSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/SimpleInstallSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/StylesGuideSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/TestingInstallSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/UpgradeSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/UserAccountSteps.java
src/test/java/org/openmrs/contrib/qaframework/automation/VitalsAndTriagingSteps.java

Goal: 
Organize imports to follow OpenMRS import convention

RATEST-277: Organize imports to follow OpenMRS import convention

---

qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/ManageUserAccountPage.java
qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/UserAccountSteps.java
qaframework-bdd-tests/src/test/resources/features/refapp-2.x/06-user/users.feature

Ticket [ID](https://issues.openmrs.org/browse/RATEST-282)
Description -> Modify user account test to generate different username on n each run

RATEST-282: Modify user account test to generate different username on each run

---

.github/workflows/ocl-subscription-module.yml
.github/workflows/platform-install-advanced.yml
.github/workflows/platform-install-postgres.yml
.github/workflows/platform-install-simple.yml
.github/workflows/platform-upgrade.yml
.github/workflows/qa.yml
.github/workflows/refapp-2.x-condition.yml
.github/workflows/refapp-2x-clinical-visit.yml
.github/workflows/refapp-2x-find-Patient.yml
.github/workflows/refapp-2x-inpatient.yml
.github/workflows/refapp-2x-legacy.yml
.github/workflows/refapp-2x-patient-demograpics.yml
.github/workflows/refapp-2x-registration.yml
.github/workflows/refapp-2x-report.yml
.github/workflows/refapp-2x-user-account.yml
.github/workflows/refapp-2x-vitals-and-triaging.yml
.github/workflows/refapp-3x-clinical-visit.yml
.github/workflows/refapp-3x-login.yml
.github/workflows/refapp-3x-patient-registration.yml
.github/workflows/refapp-3x-patient-search.yml
.github/workflows/refapp-3x-settings.yml
.github/workflows/refapp-3x-vitals-and-triage.yml

Goal:
To locate cucumber.properties and test properties files during ci.

RATEST-258: Locate cucumber.properties and test properties files on ci

---

.github/workflows/platform-install-postgres.yml
qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/ClinicalVisitSteps.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-284)
Description -> Fix failing build plan on github actions

RATEST-284: Fix failing build plan on github actions

---

qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/ClinicalVisitSteps.java

Ticket ->  [RATEST-279](https://issues.openmrs.org/browse/RATEST-279)
Fixed -> End Visit User story to run on Firefox engine

RATEST-279: Fix test to run on firefox browser

---

qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/HtmlFormsPage.java
qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/FormSteps.java

https://issues.openmrs.org/browse/RATEST-291

RATEST-291:RefApp 2.x Form test is failing on github actions

---

.github/workflows/refapp-3x-clinical-visit.yml
qaframework-bdd-tests/cypress/integration/cucumber/step_definitions/refapp-3.x/04-clinical-visit/clinical-visit.js
qaframework-bdd-tests/cypress/support/commands.js

The purpose of this PR is to fix [O3-984](https://issues.openmrs.org/browse/O3-984)
Fix the failing clinical visit test after the migration
Updated the Clinical Visit E2E test and workflow
Note: The form entry component is not working in the o3 server, so 2 tests are failing

O3-984: Fix RefApp 3.x Clinical Visit E2E Test

---

.github/workflows/refapp-3x-clinical-visit.yml
qaframework-bdd-tests/cypress/integration/cucumber/step_definitions/refapp-3.x/04-clinical-visit/clinical-visit.js
qaframework-bdd-tests/cypress/support/commands.js

Reverts openmrs/openmrs-contrib-qaframework#303
We need to revert this #303 because MFE team instructed to use the previous server until there fix dev3.

Revert "O3-984: Fix RefApp 3.x Clinical Visit E2E Test"

---

.github/workflows/refapp-3x-clinical-visit.yml
.github/workflows/refapp-3x-patient-registration.yml
.github/workflows/refapp-3x-patient-search.yml
.github/workflows/refapp-3x-settings.yml
.github/workflows/refapp-3x-vitals-and-triage.yml

The purpose of this PR is to fix [O3-1017](https://issues.openmrs.org/browse/O3-1017).
- Update file paths of 3. x test workflow files.

O3-1017: Update paths of 3.x workflow files

---

qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/ConditionsSteps.java

**Description**:
This is a fix following the discussion about the subject on https://github.com/openmrs/openmrs-contrib-qaframework/pull/340

RATEST-242-patch-1: Removing redundant code in the conditions steps definition file

---

qaframework-bdd-tests/src/test/resources/features/refapp-2.x/015-reports/reports.feature
qaframework-bdd-tests/src/test/resources/org/openmrs/uitestframework/test-local.properties

https://github.com/openmrs/openmrs-contrib-qaframework/commit/afbed520d89552b1f2d1cfe5a4936ecc88f74b47

Getting Rid of DB.Host property

---

.github/workflows/platform-install-advanced.yml
.github/workflows/platform-install-postgres.yml
.github/workflows/platform-install-simple.yml
.github/workflows/platform-upgrade.yml
.github/workflows/qa.yml
.github/workflows/refapp-2x-clinical-visit.yml
.github/workflows/refapp-2x-condition.yml
.github/workflows/refapp-2x-find-Patient.yml
.github/workflows/refapp-2x-form.yml
.github/workflows/refapp-2x-inpatient.yml
.github/workflows/refapp-2x-login.yml
.github/workflows/refapp-2x-patient-allergies.yml
.github/workflows/refapp-2x-patient-demographics.yml
.github/workflows/refapp-2x-patient-record.yml
.github/workflows/refapp-2x-patient-visit.yml
.github/workflows/refapp-2x-person.yml
.github/workflows/refapp-2x-phoneNumberValidation.yml
.github/workflows/refapp-2x-provider.yml
.github/workflows/refapp-2x-registration.yml
.github/workflows/refapp-2x-report.yml
.github/workflows/refapp-2x-roles-and-privileges.yml
.github/workflows/refapp-2x-user-account.yml
.github/workflows/refapp-2x-visit-type.yml
.github/workflows/refapp-2x-vitals-and-triaging.yml

[Update paths for RefApp 2.x and Platform files](https://issues.openmrs.org/browse/RATEST-320)

Update paths for RefApp 2.x and platform files

---

.github/workflows/platform-install-advanced.yml
.github/workflows/platform-install-postgres.yml
.github/workflows/platform-install-simple.yml
.github/workflows/platform-upgrade.yml

Ticket [ID](https://issues.openmrs.org/browse/RATEST-320)

Fix platform ui tests

---

.github/workflows/refapp-2x-open-Concept-Lab.yml
qaframework-bdd-tests/package.json
qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/ConfigureMetadataPage.java
qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/OpenConceptLabPage.java
qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/OpenConceptLabSuccessPage.java
qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/SubscriptionPage.java
qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/RunTest.java
qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/OpenConceptLabSteps.java
qaframework-bdd-tests/src/test/resources/features/refapp-2.x/16-openConceptLab/openConceptLab.feature

Description of what I did:
I created the following files:
-  open-Concept-Lab.yml file
- made changes on package.json file
- modified ConfigureMetadataPage
- Created OpenConceptLabPage
- Created OpenConceptLabSuccessPage
- Created SubscriptionPage
- Modified RunTest
- Created OpenConceptLabSteps
- Created openConceptLab.feature
Issue I worked on:
https://issues.openmrs.org/browse/RATEST-275

RATEST-275:NEW E2E Test: Manage OCL Subscription Workflow

---

qaframework-bdd-tests/pom.xml
qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/helper/Page.java
qaframework-legacy-tests/pom.xml

upgrade selenium version to latest version.

Upgrade selenium version 

---

qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/ConditionsSteps.java
qaframework-bdd-tests/src/test/resources/features/refapp-2.x/12-condition/conditions.feature

Fixed typos in the conditions feature file

Fix typos in the conditions workflow test

---

.github/workflows/ocl-subscription-module.yml
.github/workflows/qa.yml
.github/workflows/refapp-2x-clinical-visit.yml
.github/workflows/refapp-2x-condition.yml
.github/workflows/refapp-2x-find-Patient.yml
.github/workflows/refapp-2x-form.yml
.github/workflows/refapp-2x-inpatient.yml
.github/workflows/refapp-2x-legacy.yml
.github/workflows/refapp-2x-login.yml
.github/workflows/refapp-2x-open-concept-lab.yml
.github/workflows/refapp-2x-patient-allergies.yml
.github/workflows/refapp-2x-patient-demographics.yml
.github/workflows/refapp-2x-patient-encounter.yml
.github/workflows/refapp-2x-patient-record.yml
.github/workflows/refapp-2x-patient-visit.yml
.github/workflows/refapp-2x-person.yml
.github/workflows/refapp-2x-phoneNumberValidation.yml
.github/workflows/refapp-2x-provider.yml
.github/workflows/refapp-2x-registration.yml
.github/workflows/refapp-2x-report.yml
.github/workflows/refapp-2x-roles-and-privileges.yml
.github/workflows/refapp-2x-service.yml
.github/workflows/refapp-2x-user-account.yml
.github/workflows/refapp-2x-user.yml
.github/workflows/refapp-2x-visit-note.yml
.github/workflows/refapp-2x-visit-type.yml
.github/workflows/refapp-2x-vitals-and-triaging.yml

Removed path to   "qaframework-bdd-tests/src/**/*.*"
- "qaframework-bdd-tests/package.json"
Since we only deal with 2.x specifically.

Remove Path directory in .yml file

---

qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/helper/TestBase.java

cc @kdaud  Trial fix to the ci failing to run chrome successfully on remote machine.

Set System property to whitelistedIps

---

qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/helper/TestBase.java

Reverts openmrs/openmrs-contrib-qaframework#443

Revert "Added chrome options to fix DevToolsActivePort failures on ci"

---

qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/helper/TestBase.java

Reverts openmrs/openmrs-contrib-qaframework#447

Revert "Set System property to whitelistedIps"

---

qaframework-bdd-tests/src/test/resources/org/openmrs/uitestframework/test-bamboo.properties
qaframework-bdd-tests/src/test/resources/org/openmrs/uitestframework/test.properties
qaframework-legacy-tests/src/test/resources/org/openmrs/uitestframework/test-bamboo.properties
qaframework-legacy-tests/src/test/resources/org/openmrs/uitestframework/test.properties

Reverts openmrs/openmrs-contrib-qaframework#450

Revert "Upgrade chrome-driver to v99.0.4844 and set driver-path"

---

qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/VisitNotePage.java
qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/VisitNoteSteps.java
qaframework-bdd-tests/src/test/resources/features/refapp-2.x/07-visit/visitNote.feature

The Visit Note test had several issues with the xpaths and the steps. Fixed those with this PR.
https://issues.openmrs.org/projects/RATEST/issues/RATEST-343

RATEST-343: Fix the Visit Note tests

---

.github/pull_request_template.md

Overall, adding a pull request template to the OpenMRS QA framework can help improve the contribution process and ensure that the framework remains a reliable and effective tool for managing healthcare information.
*None.*
https://issues.openmrs.org/projects/RATEST/issues/RATEST-346
*None.*

RATEST-346: Add a pull request template

---

README.md

- Removed bamboo icon status badges
🙄  https://issues.openmrs.org/browse/RATEST-348

RATEST-348: Replace icons for bamboo build status with OpenMRS Shields

---

.github/workflows/platform-install-advanced.yml
.github/workflows/platform-install-postgres.yml
.github/workflows/platform-install-simple.yml
.github/workflows/platform-install-testing.yml
.github/workflows/platform-upgrade.yml

In this PR, The platform-related github action changes done by https://github.com/openmrs/openmrs-contrib-qaframework/pull/485 was reverted because they are not supposed to change.
*None.*
https://issues.openmrs.org/browse/RATEST-349
*None.*

RATEST-349: Revert platform related github action changes

---

.github/workflows/platform-install-advanced.yml
.github/workflows/platform-install-postgres.yml
.github/workflows/platform-install-simple.yml
.github/workflows/platform-install-testing.yml
.github/workflows/platform-upgrade.yml

- In this PR the failing platform tests are fixed. It was due to missing local test properties file. It happened due to the file renaming in the previous PR. https://github.com/openmrs/openmrs-contrib-qaframework/pull/485
*None.*
https://issues.openmrs.org/browse/RATEST-349
*None.*

RATEST-349: Fix the test local properties missing issue

---

README.md

*None.*
https://openmrs.atlassian.net/browse/O3-2934
*None.*
*None.*

Update url to the guide for setting up OpenMRS 2.x QA  framework locally

---

pom.xml
qaframework-bdd-tests/pom.xml
qaframework-legacy-tests/pom.xml

Upgrade libraries

---

qaframework-bdd-tests/pom.xml
qaframework-legacy-tests/pom.xml

Upgrade selenium to 4.11.0 and jersey to 3.0.12

---

qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/EditVitalsPage.java
qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/VitalsAndTriagingSteps.java

Update xpath for 'save button' on Edit vitals page
