openmrs/openmrs-contrib-qaframework

- .github/workflows/refapp-3x-login.yml
- cypress.json
- cypress/integration/cucumber/step_definitions/refapp-3.x/01-login/login.js
- cypress/plugins/index.js
- cypress/support/commands.js
- package.json
- src/test/resources/features/refapp-3.x/01-login/login.feature
- src/test/resources/org/openmrs/uitestframework/test-cypress.properties
The purpose of this pr is to fix [MF-532](https://issues.openmrs.org/browse/MF-532)
To give users confidence that the Login workflow of the RefApp 3.x is working as expected.
- Create a new property file to store properties
- Remove step definition files of the ocl client (Because it has been already moved to a separate project)
- Implement an E2E test for the login flow of refapp-3.x
- Create a GitHub workflow file
- Increase the max waiting time to 40 seconds (Sometimes the test server takes that much time to load the inner components but it pretends the page has been fully loaded. Therefore increasing the waiting time is essential)
- Add workflow badge to the readme file
> MF-532: Implement an E2E test for the login flow of refapp-3.x

- pom.xml
Ticket [ID](https://issues.openmrs.org/projects/RATEST/issues/RATEST-193)
Description -> : Add windows execution configuration to support devs using  windows os
> RATEST-193: Add windows execution configuration to support devs using  windows os

- cypress/integration/cucumber/step_definitions/refapp-3.x/04-clinical-visit/clinical-visit.js
- src/test/resources/features/refapp-3.x/04-clinical-visit/clinical-visit.feature
The purpose of this PR is to fix the patient deletion issue in the `3.x Clinical flow`
See: https://issues.openmrs.org/browse/RATEST-201
- Pass the UUID instead of the identifier
> Fix patient deletion issue in 3.x Clinical flow

- .github/workflows/refapp-3x-clinical-visit.yml
- .github/workflows/refapp-3x-login.yml
- .github/workflows/refapp-3x-search-and-registration.yml
- .github/workflows/refapp-3x-settings.yml
- cypress.json
The pull request is to add a new feature of attaching screen recording of failed 3. x tests and this pull request is related to the issue ticket number [RATEST-207](https://issues.openmrs.org/browse/RATEST-207).
- To allow developers/stakeholders to identify why tests failing by playing the screen recording without running them locally. 
- To save time
1. Make cypress screen recording facility turn on.
2. Make 3. x test GitHub workflows to attach the screen recordings of failed tests.
A failed test - ([Link](https://github.com/openmrs/openmrs-contrib-qaframework/actions/runs/1185617340))
> RATEST-207: Attach screen recordings of failed 3.x tests to gh-action

- docker/docker-compose-refqa.yml
Ticket [ID](https://issues.openmrs.org/browse/RATEST-233)
Description ->  Make local instance have the same versions of modules as qa-refapp
> RATEST-233: Make local instance have the same versions of modules as qa-refapp

- README.md
Goal: To add these status items into our QA dashboard. (This actually helped catch a failing platform build before even the Talk items did!)
Result:
> Added Build Statuses for Trunk, RESTWS, FHIR2, & LU

- src/test/java/org/openmrs/contrib/qaframework/automation/VitalsAndTriagingSteps.java
Ticket [ID](https://issues.openmrs.org/browse/RATEST-232)
Description -> Failure when validating the vital value of respiratory rate
> RATEST-232: Failure when validating the vital value of respiratory rate

- pom.xml
Ticket [ID](https://issues.openmrs.org/browse/RATEST-238)
Description -> Continuous Integration fails on both Github Actions and Bamboo when resolving dependencies for the referenceapplication-ui-test module. See the full [logs](https://ci.openmrs.org/browse/CONTRIB-QA-853/log)
> RATEST-238: Update refappuitests version to 2.13.0-SNAPSHOT

- pom.xml
Ticket [ID](https://issues.openmrs.org/browse/RATEST-238)
Description -> Continuous integration fails on both Github Actions and Bamboo when resolving dependency for the referenceapplication-ui-test module. See the full [logs](https://ci.openmrs.org/browse/CONTRIB-QA-883/log)
> RATEST-238x: Update refappuitests version to 2.13.0-SNAPSHOT

- pom.xml
Ticket [ID](https://issues.openmrs.org/browse/RATEST-238)
Description -> Continuous integration fails on both Github Actions and Bamboo when resolving dependency for the referenceapplication-ui-test module. See the full [logs](https://ci.openmrs.org/browse/CONTRIB-QA-883/log)
> RATEST-238: Update refappuitests version to 2.12.0-SNAPSHOT

- README.md
The purpose of this PR is to fix [O3-920](https://issues.openmrs.org/browse/O3-920).
3.X dashboard should be updated to showcase the test result of the newly created patient-search workflow.
Update the dashboard to showcase the patient-search work test result badge.
> O3-920: Add search workflow test result badge to the 3.X dashboard

- cypress.json
The pull request is to fix -
Issue ticket [O3-897](https://issues.openmrs.org/browse/O3-897)
Create cypress run mode retries to retry failing E2E tests. 
1. Create cypress retries in cypress configuration file
2. Increase runMode count to retry the failing tests.
> O3-897: Configure cypress retries to retry failing E2E tests

- pom.xml
Goal:
Get rid of the formatter version since the plugin no longer exists
> RATEST: Remove the formatter version since the plugin no longer exists

- README.md
- pom.xml
This a simple fix in the readme file and identing the pom parent file. cc @kdaud
> Fix the status badges links

- .github/workflows/refapp-3x-login.yml
- .gitignore
- qaframework-bdd-tests/cypress.json
- qaframework-bdd-tests/src/test/resources/features/refapp-3.x/01-login/login.feature
The purpose of this PR is to fix [O3-993](https://issues.openmrs.org/browse/O3-993)
Fix the failing login E2E test.
Update relevant cypress environment variables.
Updated the login E2E test and workflow
Note: The error message with the wrong login details is not shown in the UI. Because of it 2 of 3 tests are failing.
> O3-993 : Fix RefApp 3.x login E2E test

- qaframework-bdd-tests/cypress.json
- qaframework-bdd-tests/cypress/integration/cucumber/step_definitions/refapp-3.x/04-clinical-visit/clinical-visit.js
- qaframework-bdd-tests/src/test/resources/features/refapp-3.x/04-clinical-visit/clinical-visit.feature
The purpose of this PR is to fix [O3-984](https://issues.openmrs.org/browse/O3-984)
Fix the failing clinical visit tests
- Updated the Clinical Visit E2E test
- Increased the default timeout to 120 sec
- It takes around 115 seconds to load the patient dashboard if we reload the page during a test. In the form entry and programs UI, the new data doesn't appear unless we refresh it. So it's not possible to remove the reload function at the moment.
-  Also the test consumes around 850MB when running, because it downloads all the modules before displaying the UI (due to the offline mode).
> O3-984: Fix RefApp 3.x Clinical Visit E2E Test

- qaframework-bdd-tests/cypress/integration/cucumber/step_definitions/refapp-3.x/01-login/login.js
The pull request is to fix the 3. x login tests case and this pull request is related to the issue ticket number [O3-1030](https://issues.openmrs.org/browse/O3-1030).
Updated the error message in the login to fit with the new UI validation message.
> O3-1030: Update E2E 3.x Login test case error message

- qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/AllergiesSteps.java
- qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/ClinicalVisitSteps.java
- qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/ConditionsSteps.java
- qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/FindPatientSteps.java
- qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/InpatientSteps.java
- qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/VitalsAndTriagingSteps.java
Creation of test patient should be invoked after the test logged into the system. However, these tests in context are failing with actions but passing with bamboo. cc: @sherrif10
> RATEST: Fix the RefApp 2.x tests failing github actions

- .github/workflows/ocl-subscription-module.yml
- .github/workflows/qa.yml
- .github/workflows/refapp-2x-clinical-visit.yml
- .github/workflows/refapp-2x-condition.yml
- .github/workflows/refapp-2x-find-Patient.yml
- .github/workflows/refapp-2x-form.yml
- .github/workflows/refapp-2x-inpatient.yml
- .github/workflows/refapp-2x-legacy.yml
- .github/workflows/refapp-2x-login.yml
- .github/workflows/refapp-2x-patient-allergies.yml
- .github/workflows/refapp-2x-patient-demographics.yml
- .github/workflows/refapp-2x-patient-record.yml
- .github/workflows/refapp-2x-patient-visit.yml
- .github/workflows/refapp-2x-person.yml
- .github/workflows/refapp-2x-phoneNumberValidation.yml
- .github/workflows/refapp-2x-provider.yml
- .github/workflows/refapp-2x-registration.yml
- .github/workflows/refapp-2x-report.yml
- .github/workflows/refapp-2x-roles-and-privileges.yml
- .github/workflows/refapp-2x-user-account.yml
- .github/workflows/refapp-2x-visit-type.yml
- .github/workflows/refapp-2x-vitals-and-triaging.yml
- .github/workflows/refapp-3x-clinical-visit.yml
- .github/workflows/refapp-3x-login.yml
- .github/workflows/refapp-3x-patient-registration.yml
- .github/workflows/refapp-3x-patient-search.yml
- .github/workflows/refapp-3x-settings.yml
- .github/workflows/refapp-3x-vitals-and-triage.yml
What this does is determine (for PRs only) which jobs should be run based on which files were touched. I noticed that, e.g., when looking at [this PR](https://github.com/openmrs/openmrs-contrib-qaframework/pull/379) none of the 3.x jobs were being run... never mind the actual job that was supposed to fix. We should actually probably limit this down further for pushes etc. as we can only have 20 jobs run at one time, so, e.g., on push other jobs aren't necessarily being run.
PS This PR itself should have no jobs run since it didn't touch any of the files.
> Segregate which workflows get run based on which files are touched

- qaframework-bdd-tests/package.json
The purpose of this PR is to update the cypress version and fix failing E2E tests.
Update the cypress version.
> Update cypress version and fix failing E2E test.

- README.md
- qaframework-bdd-tests/cypress.json
Issue link
https://issues.openmrs.org/browse/RATEST-327
Description:
I think its worth for us to change our cloud instance to point to https://dev3.openmrs.org/openmrs/spa since it is were latest changes are deployed 
cc @sherrif10 @kdaud @dkayiwa
> RATEST-327: cypress baseUrl should point to https://dev3.openmrs.org/openmrs/spa

- qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/page/VisitNotePage.java
- qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/VisitNoteSteps.java
- qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/VitalsAndTriagingSteps.java
These changes are catering for the following resolutions
1. Resolve visibility exceptions in visitNote according to this https://github.com/openmrs/openmrs-contrib-qaframework/runs/7000791006?check_suite_focus=true.
2. Use javascript executor instead of clickable to enable browser find a desired element to click on.
cc @kdaud
> Resolve All firefox failures

- qaframework-bdd-tests/src/main/java/org/openmrs/contrib/qaframework/helper/TestBase.java
Basing on the continuing ci failures after a number of rebuilds as [reflected here](https://ci.openmrs.org/download/CONTRIB-QA-FRAMEWORK/build_logs/CONTRIB-QA-FRAMEWORK-1654.log). i believe this solution might resolve ci failures by adding an argument to the chromeOptions starting  chrome webdriver.
cc @dkayiwa @ibacher  @kdaud
> Added chrome options to fix DevToolsActivePort failures on ci

- qaframework-bdd-tests/cypress.json
2.x OCL Subscription Module tests were failing due to an incorrect baseURL.
Updated the baseURL with the correct url.
**Tested with GitHub actions:**
https://issues.openmrs.org/projects/RATEST/issues/RATEST-341
> RATEST-341: Fix the base url of cypress tests

- qaframework-bdd-tests/src/test/java/org/openmrs/contrib/qaframework/automation/ClinicalVisitSteps.java
- qaframework-bdd-tests/src/test/resources/features/refapp-2.x/14-clinicalVisit/clinicalVisit.feature
The RefApp 2.x Clinical Visit Test workflow is currently failing. Specifically, it fails when attempting to save a visit note in the Complete visit note user story.
Tested with GitHub actions:
https://issues.openmrs.org/browse/RATEST-344
> RATEST-344: Fix the failing RefApp 2.x Clinical Visit Test

- qaframework-bdd-tests/pom.xml
The tests were failing due a mismatch in the node version. We had configured it to run the workflows with node 16 while the version we install through pom.xml was node 15. So the pom.xml was updated to use node 16.
*None.*
https://issues.openmrs.org/projects/RATEST/issues/RATEST-352
*None.*
> RATEST-352: Bump node version to 16.20.0
